php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
js: false
ts: false
css: false
vue: false
py: false
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
